version: '2'
services:
  osm-ro:
    image: ${HUB_REPO}/osm-ro:${COMMIT_ID}
    container_name: osm-ro
    ports:
      - "9090:9090"
    volumes:
      - /tmp/osm/openmano/logs:/opt/openmano/logs
  osm-so:
    image: ${HUB_REPO}/osm-so:${COMMIT_ID}
    container_name: osm-so
    privileged: true
    ports:
      - "8008:8888"
      - "4567:4567"
      - "4568:4568"
    volumes:
      - /tmp/osm/rift/:/var/log/rift/
    depends_on:
      - osm-ro
  osm-ui:
    image: ${HUB_REPO}/osm-ui:${COMMIT_ID}
    container_name: osm-ui
    environment:
      - API_SERVER=osm-so
    ports:
      - "9443:8443"
    depends_on:
      - osm-so
    links:
      - osm-so
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: ${NET_MTU}
