version: '2'
services:
  RO:
    image: ${HUB_REPO}/osm-ro:${COMMIT_ID}
    container_name: osm-ro
    ports:
      - "9090:9090"
    volumes:
      - /tmp/osm/openmano/logs:/opt/openmano/logs
  VCA:
    image: ${HUB_REPO}/osm-vca:${COMMIT_ID}
    container_name: osm-vca
    ports:
      - "443:443"
      - "17070:17070"
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /run/systemd:/run/systemd
      - /usr/bin/systemctl:/usr/bin/systemctl
      - /etc/systemd/system:/etc/systemd/system
      - /var/lib/lxd/:/var/lib/lxd/
      - /etc/default/lxd-bridge:/etc/default/lxd-bridge
  SO-UI:
    image: ${HUB_REPO}/osm-so-ui:${COMMIT_ID}
    container_name: osm-so-ui
    privileged: true
    ports:
    - "8008:9999"
    - "9443:8443"
    - "4567:4567"
    - "4568:4568"
    volumes:
    - /tmp/osm/rift/:/var/log/rift/
    depends_on:
    - RO
    - VCA