version: '2'
services:
  osm-ro:
    image: ${HUB_REPO}/osm-ro:${COMMIT_ID}
    container_name: osm-ro
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - /var/log/osm/openmano/logs:/opt/openmano/logs
  osm-vca:
    image: ${HUB_REPO}/osm-vca:${COMMIT_ID}
    container_name: osm-vca
    restart: always
    environment:
      - NET_MTU=${NET_MTU}
    ports:
      - "443:443"
      - "17070:17070"
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /run/systemd:/run/systemd
      - /usr/bin/systemctl:/usr/bin/systemctl
      - /etc/systemd/system:/etc/systemd/system
      - /var/lib/lxd/:/var/lib/lxd/
      - /etc/default/lxd-bridge:/etc/default/lxd-bridge
  osm-so:
    image: ${HUB_REPO}/osm-so:${COMMIT_ID}
    container_name: osm-so
    restart: always
    privileged: true
    ports:
      - "8008:8888"
      - "4567:4567"
      - "4568:4568"
    volumes:
      - /var/log/osm/rift/:/var/log/rift/
    depends_on:
      - osm-ro
      - osm-vca
  osm-ui:
    image: ${HUB_REPO}/osm-ui:${COMMIT_ID}
    container_name: osm-ui
    restart: always
    environment:
      - API_SERVER=${API_SERVER}
    ports:
      - "9443:8443"
    depends_on:
      - osm-so
    links:
      - osm-so
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: ${NET_MTU}
